title: Calculadora Lords
description: Fazer calculos de recursos, coletas, produções, acelerações e calculos de confiança
show_downloads: true
google_analytics: UA-120906850-1
theme: jekyll-theme-merlot
